### ISSUE TITLE
Calculation of saturation 

### ISSUE THREAD

**Issue by KayalvizhiSadayappan** [Li-Reactive-Water-Group/HBV-BioRT#20]
**Describe the bug**
The output of water storage from HBV-light is total water storage. So, while calculating saturation, water storage should be divided by  (porosity*layer thickness). Currently, porosity is not used for calculating saturation.

**To Reproduce**
- *Upload your input files with the bug report*.
- Model version number.
- Time step when problem occurs.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Unix]

**Additional context**

**Comment by WeiZhiWater** [comment]
bug fixed in react. c 

satn = subcatch[ksub].ws[kstep][kzone] / (depth * porosity);
