### ISSUE TITLE
Error in equilibrium constant (Keq or C) of mineral reactions (lookup.c)

### ISSUE THREAD

**Issue by KayalvizhiSadayappan** [Li-Reactive-Water-Group/HBV-BioRT#21]
**Describe the bug**
The equilibrium constant of mineral reactions are not updated properly when secondary species are present in mineral reaction stoichiometry.

**To Reproduce**
[B_1.zip](https://github.com/Li-Reactive-Water-Group/HBV-BioRT/files/6281115/B_1.zip)

**Expected behavior**
The CO2(aq) should be about 1.2E-3 mol/l according to equilibrium constant of CO2(*g) mineral in input but currently CO2(aq) values are too high.
![3](https://user-images.githubusercontent.com/70716152/114088941-9271c780-9883-11eb-89b7-1b9108056e9c.png)

**Desktop (please complete the following information):**
 - OS: Unix

**Additional context**
On checking the code, the error is in lookup.c code. As can be seen in attached figure (red box), in line 495, keq_kin_all is changed according to the keq of secondary species if secondary species are present in products of mineral reaction. However, in line 507, the keq of mineral reaction is read in directly, thereby overwriting the changes required due to presence of secondary species. Here, the keq value read should be added to keq_kin_all rather than being directly assigned to it. 
![1](https://user-images.githubusercontent.com/70716152/114088712-4c1c6880-9883-11eb-9ebe-f9160068f384.png)
So, I modified the code as follows (blue boxes) to correct it. A variable keq_sec was created to temporarily store the modification to be made and later added to keq_kin_all.
![2](https://user-images.githubusercontent.com/70716152/114088735-52aae000-9883-11eb-81dc-c887610bdea3.png)

This modification gave me the expected result.
![4](https://user-images.githubusercontent.com/70716152/114088775-5fc7cf00-9883-11eb-9d7b-1abae4427207.png)

**Comment by WeiZhiWater** [comment]
Kayal:

Can you also plot carbonate as a function of pH in the UZ and LZ zone to further test the equilibrium (secondary) reaction, to see whether the code could correctly handle this? If necessary, change precipitation pH to a larger range to test it (e.g., 3 < pH < 12). If you got a similar plot in the UZ and LZ zone, then we will update the code. 

![image](https://user-images.githubusercontent.com/13573170/114100643-9c4ef700-9892-11eb-9385-57d761530413.png)

**Comment by WeiZhiWater** [comment]
For now, we don't have the function of time-series precipitation concentration. But you can test it like this, set a low initial pH in the UZ/LZ zone and set a high pH in precipitation concentration, so over time, you will get a gradual pH increase in the UZ/LZ zone and the stream, so you can plot the carbonate as a function of pH.

**Comment by KayalvizhiSadayappan** [comment]
I will run the tests and let you know, Wei

**Comment by KayalvizhiSadayappan** [comment]
The "lookup.c" code was updated to read in and modify the reaction rates correctly.
