### ISSUE TITLE
Mass balance issue as per email with Li Li

### ISSUE THREAD

**Issue by DevonKerins** [Li-Reactive-Water-Group/HBV-BioRT#41]
**Describe the bug**
There seems to be a mass balance issue with the sorption. 

The attached excel sheet has the outputs and plots from the attached input files.

CoalCreek 1 is a base case. Here is can reproduce the measured data in the right range however, I cannot replicate the peaking behavior of DOC

CoalCreek2 I have increased the X- to 10, in the plots you can see the XDOC increases by multiple orders of magnitude greater than the DOC concentration in the UZ. However, when XDOC decreases you would assume the mass of DOC released would be large enough that the DOC concentration in the UZ should increase as well. You can see that DOC doesn't increase instead follows generally the same pattern as XDOC and decreases as well. In this case, I cannot increase the SSA enough before the SOC is depleted enough to bring the DOC levels back up to the magnitude of the measured data.

CoalCreek3 is the case where I have increased the X- to 10 in the cini.txt file and increased the Keq from -1 to -0.25. Here the XDOC concentration remains exactly the same as CoalCreek2 but the DOC concentrations increases. I have increased the SSA to bring up the reaction rates and DOC concentrations back to the measured values and I don't run into the same problem as CoalCreek2 with the SOC being too depleted. I still see the same XDOC and DOC behavior as in the previous two cases and thus cannot capture the DOC peaks.

**Additional context**
[CoalCreek1.zip](https://github.com/Li-Reactive-Water-Group/HBV-BioRT/files/8789848/CoalCreek1.zip)
[CoalCreek3.zip](https://github.com/Li-Reactive-Water-Group/HBV-BioRT/files/8789850/CoalCreek3.zip)
[CoalCreek2.zip](https://github.com/Li-Reactive-Water-Group/HBV-BioRT/files/8789851/CoalCreek2.zip)
[testing_sorption_20220527.xlsx](https://github.com/Li-Reactive-Water-Group/HBV-BioRT/files/8789916/testing_sorption_20220527.xlsx)

![image](https://user-images.githubusercontent.com/70672312/170793394-cadef3c2-86a4-459d-97a6-fff0e0330b4a.png)

**Comment by KayalvizhiSadayappan** [comment]
Hi Devon,

The reason increasing X- doesn't change the dynamics is because "adsorption" can't be captured by equilibrium reaction. I don't think there is a problem with mass balance.

Thanks,
Kayal

**Comment by DevonKerins** [comment]
Files for sorption comparisons 05/30/202
[CoalCreek1(1).zip](https://github.com/Li-Reactive-Water-Group/HBV-BioRT/files/8801424/CoalCreek1.1.zip)
[CoalCreek2(1).zip](https://github.com/Li-Reactive-Water-Group/HBV-BioRT/files/8801426/CoalCreek2.1.zip)
2

**Comment by KayalvizhiSadayappan** [comment]
There was no mass balance issue when analysed in detail.
